name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Environment
      run: |
        cd docker
        docker-compose build
        docker-compose run -d --name tex4tum tex4tum bash
        docker ps -a
    - name: Build
      run : |
        docker exec tex4tum bash -c "bundle install && make build"
        docker exec tex4tum bash -c "echo '# This branch is for deployment only' >> _site/README.md"
    - name: Prepare Deployment
      if: github.ref == 'refs/heads/master'
      run: |
        apt-get update && apt-get install -y rsync
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: _site
        single-commit: true
        silent: true
